
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_1e64ccce06bec53?serverTimezone=Asia/Seoul&reconnect=true
    username: b7d24238db29fe
    password: 39243154

  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8002